fixed the >>>cp: are the same file<<< error
esm-tools/esm_master pull request #21
Opened 2020-10-01 11:05 UTC by denizural

As Laurent Oziel mentioned during the workshop today, FESOM compilation (`esm_master comp-fesom-1.4`) ends with an error like 
`subprocess.CalledProcessError: Command '['cp', 'fesom-2.0/bin/fesom.x', 'fesom-2.0/bin']' returned non-zero exit status 1.`

Although this is not a real error, subprocess.run() raises an exception since the shell return status ($?) is not 0. The reason is FESOM executables are hard linked and they share the same inode numbers. Therefore, copying these files on each other causes non-zero return.

I solved this issue by wrapping the `subprocess.run()` inside a `try-except` block and simply ignore the CalledProcessError exception.

Now the compilation  completes without any errors but only the message:

> cp: ‘fesom-1.4/bin/fesom’ and ‘fesom-1.4/bin/fesom’ are the same file

This can also be avoided (if you want) by adding `2>/dev/null` to the copy command in task.py.

2020-10-02 09:33 UTC, mandresm requested changes
This will definitely solve the problem, however I would suggest that we don't use a `try` here and address the issue straight away. If we use a `try` here, catching bugs in the copying of the binaries might be more difficult in the future. Also, when checking the commands (`esm_master install-fesom-1.4 -c`) the last command is:
```
cp fesom-1.4/bin/fesom fesom-1.4/bin
```
I think this is a bit dismissive. What I would suggest is that this command is directly not added if the origin path for the copy is the same as the target path, which is what is happening in this case. This is more in the line with the changes we've been doing in the past to try to fix this sort of errors. For example, one could substitute the lines 298-318 with the following
```
                            # MA: build the paths give as input to ``cp`` for copying
                            # the binary from the origin path to the target path
                            bin_origin = task.package.destination + "/" + binfile
                            bin_target = toplevel + "/" +  task.package.bin_type
                            # MA: compare the target and the origin path, if they
                            # are the same, copying is not needed
                            path2bin_origin = "/".join(bin_origin.split('/')[:-1])
                            copy_bool = path2bin_origin != bin_target
                            # MA: add the other two conditions
                            copy_bool &= not os.path.exists(toplevel_bin_path) or clean_command
                            if copy_bool:
                                command_list.append(
                                    "cp "
                                    + bin_origin
                                    + " "
                                    + bin_target
                                )   
                                real_command_list.append(
                                   "cp "
                                    + bin_origin
                                    + " "
                                    + bin_target
                                )
```

2020-10-06 12:30 UTC, pgierz requested changes
I think the Pathlib stuff will need to be a general overhaul at some point. We have another big overhaul with the logging changes @seb-wahl wanted...

Only two small thing: I'd remove the line continuations, and I maybe the should_copy_files can be defined in one go.

2020-10-06 12:30 UTC, denizural commented
I made another commit after the discussion. I checked the compilation using FESOM 1.4.  

Here are what I did

### 1) additon of `pathlib`
- I believe that pathlib module (Python 3.4, 2014) is a much better tool to use for constructing the directories. In the future we need to gradually refactor the code using that.
- Functions like `resolve()` or `absolute()`, `parent` are extremely useful and they remove the requirement for error-prone indexings. Eg. `binfile.split("/")[-1]`

### 2) More meaningful variable names for readability:
- I think ESM-Tools codes suffer from a good naming convention. `clean_command` looks like a string rather than a boolean command. Similarly `path2bin_origin` is the parent directory but it is hard to understand. Maybe `binary_file_parent` is better.

### 3) More "Pythonic" code:
- Constructions of the command strings span over multiple lines and often repeated (unnecessary duplication). 
- I simply construct the command strings like:
`cmd_str = "  ".join(["cp", str(binary_file_path), str(bin_path_target)])`
- and simply append them to the command lists: Eg. 
`command_list.append(cmd_str)`
`real_command_list.append(cmd_str)`
- So that the duplications are avoided and readability is better

2020-10-06 12:33 UTC, denizural commented
> 
> 
> I think the Pathlib stuff will need to be a general overhaul at some point. We have another big overhaul with the logging changes @seb-wahl wanted...
> 
> Only two small thing: I'd remove the line continuations (something we can automatically solve if we all agree to a code-formatter), and maybe the should_copy_files can be defined in one go.

Yes, but quite recently I switched to the PEP 8 standards and obey the Benevolent Dictator For Life:
https://www.python.org/dev/peps/pep-0008/#maximum-line-length

2020-10-06 12:42 UTC, pgierz commented
Here's an example of what I had in mind regarding code formatting: https://black.readthedocs.io/en/stable/index.html

2020-10-06 13:13 UTC, denizural commented
> 
> 
> Here's an example of what I had in mind regarding code formatting: https://black.readthedocs.io/en/stable/index.html

Black formatting looks really cool!

2020-10-07 05:15 UTC, pgierz commented
@denizural, if you want, we can add it to automatically: here's how to put it into automatic testing for code style compliance. We could add that to all the esm sub packages.

https://github.com/esm-tools/esm_version_checker/blob/master/.github/workflows/python-package.yml

2020-10-07 14:44 UTC, mandresm approved these changes

2020-10-07 14:50 UTC, mandresm requested changes
On my side I have some suggestions before it gets merged:

- [x] test `esm_master install-echam-6.3.04p1`, check that the binary is in `bin` folder and it does not crash during compilation
- [x] test recompile echam
- [x] test `esm_master install-awicm-1.0`, check that the binaries are in `bin` folder and it does not crash during compilation
- [x] test recompile awicm
- [x] test compile fesom
- [x] test recompile fesom
- [x] make sure you bumpversion (`bumpversion patch`, `git push`, `git push --tags`). This should be done at the end, right before merging.

2020-10-07 21:21 UTC, mandresm commented
I fixed an issue with recompilation of fesom. Now it should all work. I also passed again `black` to make sure my edits were well formatted.

2020-10-07 21:21 UTC, mandresm approved these changes

2020-10-08 10:54 UTC, merged